import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  homeSidebar: [{ type: "autogenerated", dirName: "home" }],
  osSidebar: [{ type: "autogenerated", dirName: "os" }],
  toolSidebar: [{ type: "autogenerated", dirName: "tools" }],
};

export default sidebars;
