import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    homeSidebar: [{ type: 'autogenerated', dirName: 'home' }],
    nixosSidebar: [{ type: 'autogenerated', dirName: 'nixos' }],
    toolSidebar: [{ type: 'autogenerated', dirName: 'tools' }],
};

export default sidebars;
