import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    homeSidebar: [{ type: 'autogenerated', dirName: 'home' }],
    tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
};

export default sidebars;
